---
fabric_name: EVPN_VXLAN_FABRIC

underlay_multicast: true
evpn_multicast: true

# Spine Switches
spine:
  defaults:
    platform: cEOS
    bgp_as: 65000
    loopback_ipv4_pool: 192.0.255.0/24
  nodes:
    - name: Spine1-J-2
      id: 1
      mgmt_ip: 192.168.0.11/24

l3leaf:
  defaults:
    platform: cEOS
    loopback_ipv4_pool: 192.0.255.0/24
    loopback_ipv4_offset: 2
    vtep_loopback_ipv4_pool: 192.0.254.0/24
    uplink_interfaces: ['Ethernet1']
    uplink_switches: ['Spine1-J-2']
    uplink_ipv4_pool: 172.30.255.0/24
    mlag_interfaces: ['Ethernet47', 'Ethernet48']
    mlag_peer_ipv4_pool: 10.255.252.0/24
    mlag_peer_l3_ipv4_pool: 10.255.251.0/24
    virtual_router_mac_address: 00:1c:73:00:dc:01
    spanning_tree_mode: mstp
    spanning_tree_priority: 16384
  node_groups:
    - group: pod0
      bgp_as: 65101
      nodes:
        - name: Leaf11-T3-3
          id: 1
          mgmt_ip: 192.168.0.21/24
          uplink_switch_interfaces: ['Ethernet1']
        - name: Leaf12-T3-4
          id: 2
          mgmt_ip: 192.168.0.22/24
          uplink_switch_interfaces: ['Ethernet2']
    - group: pod1
      bgp_as: 65102
      nodes:
        - name: Leaf21-Jp-5
          id: 3
          mgmt_ip: 192.168.0.23/24
          uplink_switch_interfaces: ['Ethernet3']
        - name: Leaf22-Jp-6
          id: 4
          mgmt_ip: 192.168.0.24/24
          uplink_switch_interfaces: ['Ethernet4']

p2p_uplinks_mtu: 9214
